### ISSUE TITLE
Error when development flag is passed without a development field in config

### ISSUE THREAD

**Issue by trevorgerhardt** [componentjs/watcher.js#5]
Need to check if `development` exists before trying to access it's properties. https://github.com/componentjs/watcher.js/blob/master/index.js#L147

**Comment by timaschew** [comment]
is it fixed with your commit? https://github.com/componentjs/watcher.js/commit/459850741126179d5233b9d7d000267a94437b1f

**Comment by trevorgerhardt** [comment]
Yup!
